# Generated by Django 3.1.1 on 2020-10-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='invetory',
            new_name='inventory',
        ),
    ]
