# Generated by Django 3.1 on 2020-09-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='copies',
            field=models.IntegerField(default=0),
        ),
    ]
