# Generated by Django 3.1.1 on 2020-09-23 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200923_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='return_date',
            new_name='expire_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=4),
        ),
        migrations.AddField(
            model_name='book',
            name='replacement_cost',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('method', models.CharField(max_length=32)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='invetory',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='main.inventory'),
            preserve_default=False,
        ),
    ]
