# Generated by Django 3.1.1 on 2020-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200930_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_author',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book_author',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
