# Generated by Django 3.1.1 on 2020-09-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200930_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_author',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
    ]
